[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM3
monitor_port = COM3
lib_deps =
    adafruit/Adafruit Fingerprint Sensor Library@^2.1.3
    bblanchon/ArduinoJson@^7.0.4
    olikraus/U8g2@^2.36.2
